version: "3.8"
services:
  issabel:
    image: cubicerp/issabel:latest
    container_name: issabel
    privileged: true
    hostname: pbx.codlinx.com.br
    restart: always
    environment:
      TZ: America/Sao_Paulo # Defina o fuso horário
    ports:
      - "5555:80" # Porta HTTP
      - "45555:443" # Porta HTTPS
      - "5060:5060/udp" # Porta SIP
      - "5061:5061/tcp" # Porta SIP-TLS
      - "10000-20000:10000-20000/udp" # Portas RTP
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - issabel-etc:/etc
      - issabel-data:/var/lib

volumes:
  issabel-etc:
    driver: local
  issabel-data:
    driver: local
